Add address validation and matching
klingtnet/rosc pull request #20
Opened 2021-09-30 21:54 UTC by DrLuke

Added address module with following features:
* Address validation
* Address matching

The validation is differentiates between method and message addresses, as defined by the OSC specification. Address matching uses either direct comparison or regex for addresses with wildcards.

I've tried to cover all kinds of cases with tests but I'm sure I've missed something.

👋 This is my first time contributing to a rust project, so feedback ony my code is very welcome!

2021-10-01 06:26 UTC, klingtnet commented
I'm glad to hear that `rosc` will be your first Rust 🦀 contribution!  I try to review your changes as soon as possible but expect it to take a couple of days.

> The validation is differentiates between method and message addresses, as defined by the OSC specification

Can you link to the specification section where method and addresses are defined so I can verify the implementation?

2021-10-01 07:46 UTC, DrLuke commented
> > The validation is differentiates between method and message addresses, as defined by the OSC specification
> 
> Can you link to the specification section where method and addresses are defined so I can verify the implementation?

Sure! [Here](http://opensoundcontrol.org/spec-1_0.html) what I call a *method address* is explained under **OSC Address Spaces and OSC Addresses** and a *message address* is right below in **OSC Message Dispatching and Pattern Matching**. (Sorry page doesn't have chapter anchors :disappointed: )

What surprised me is that method addresses can't contain any wildcars, only the address in a message can. I think I've always seen this implemented the other way :smile:

2021-10-05 10:42 UTC, klingtnet requested changes

2021-10-05 10:47 UTC, klingtnet commented
Sorry, the GitHub UI confused me again.  I already added the review suggestions four days ago but forgot to press the _request changes_ button.

2021-10-06 20:20 UTC, DrLuke commented on Cargo.toml
> +edition = "2021"
I was wondering about that when I read that in a SO answer but then forgot about it 😅

2021-10-16 17:07 UTC, klingtnet commented
Waits on https://github.com/DrLuke/rosc/pull/1 to be merged.

2021-11-18 20:11 UTC, klingtnet commented
Hey 🖖🏻 

Just wanted to let you know that I'm still alive and will merge this PR soon, hopefully Sunday.  Sorry for the delay.

2021-11-21 11:03 UTC, klingtnet approved these changes

2021-11-21 11:05 UTC, klingtnet commented
Finally, it's time for a merge.  This will be included with the `0.6.0` I'm about to release.
@DrLuke  Thanks again!

2021-11-21 11:05 UTC, merged